name: " Feature Request"
description: Crear un nuevo ticket para una nueva solicitud de funci贸n
title: " [REQUEST] - <title>"
labels: [
  "question"
]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Solicitud de funci贸n / caracter铆stica
      description: Por favor, descr铆belo.
      placeholder: Una descripci贸n clara y concisa del feature.
      value: "Me gustar铆a que [...]"
    validations:
      required: true
  - type: textarea
    id: propuesta
    attributes:
      label: Propuesta de soluci贸n
      description: Por favor, descr铆belo.
      placeholder: Una descripci贸n clara y concisa de lo que quieres que ocurra.
    validations:
      required: false
  - type: textarea
    id: alternativa
    attributes:
      label: Alternativas consideradas
      description: Por favor, descr铆belas.
      placeholder: Una descripci贸n clara y concisa de las soluciones o caracter铆sticas alternativas que has considerado.
    validations:
      required: false
  - type: textarea
    id: contexto
    attributes:
      label: Contexto adicional
      description: Por favor, descr铆belo.
      placeholder: A帽ade aqu铆 cualquier otro contexto o capturas de pantalla sobre la solicitud de funci贸n.
    validations:
      required: false